name: $name
version: $version
main: io.github.lumine1909.cartography.Cartography
api-version: $apiVersion
authors:
  - Lumine1909
commands:
  getimage:
    permission: cartography.getimage
  getmap:
    permission: cartography.getmap
permissions:
  cartography.getimage:
    default: true
  cartography.getmap:
    default: op
  cartography.bypasscd:
    default: op
  cartography.bypassmax:
    default: op