name: Cartography
version: '1.7'
main: io.github.lumine1909.cartography.Cartography
authors: [Lumine1909]
api-version: 1.13
commands:
  getimage:
    usage: /getimage <Method> <URL> [Height] [Width]
    permission: cartography.getimage
permissions:
  cartography.getimage:
    default: true
  cartography.bypass:
    default: op
  cartography.shulker:
    default: op
  cartography.compress:
    default: op