name: Cartography
version: '${project.version}'
main: io.github.lumine1909.cartography.Cartography
authors: [Lumine1909]
api-version: 1.17
commands:
  getimage:
    usage: /getimage <URL> [Height] [Width]
    permission: cartography.getimage
permissions:
  cartography.getimage:
    default: true
  cartography.bypass:
    default: op